
CONFIG_PATH ?= ""
DATABASE_PASSWORD ?= ""
ALPHAVANTAGE_API_KEY ?= ""

run:
	CONFIG_PATH=$(CONFIG_PATH) \
	DATABASE_PASSWORD=$(DATABASE_PASSWORD) \
	FINANCIAL_API_ALPHAVANTAGE_API_KEY=$(ALPHAVANTAGE_API_KEY) \
	go run ./cmd/main.go
