server:
  host: 127.0.0.1
  port: 8080
  shutdown_timeout: 30s

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  name: "etldb"

financial_api:
  alphavantage:
    base_url: "https://www.alphavantage.co/query"
    api_key: ""
